create or replace TABLE INSHORTS_DB.INTEGRATION.INT_DIM_CONTENT (
	CONTENT_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CONTENT_ID VARCHAR(16777216) NOT NULL,
	PUBLISHED_AT TIMESTAMP_NTZ(9),
	NEWSLANGUAGE VARCHAR(16777216),
	CATEGORIES VARCHAR(16777216),
	AUTHOR VARCHAR(16777216),
	RECORD_HASH NUMBER(38,0),
	EFFECTIVE_START_DT DATE NOT NULL,
	EFFECTIVE_END_DT DATE NOT NULL,
	IS_CURRENT BOOLEAN NOT NULL,
	BATCH_ID NUMBER(38,0) NOT NULL,
	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL,
	UPDATED_TS TIMESTAMP_NTZ(9),
	primary key (CONTENT_SK)
);
