create or replace TABLE INSHORTS_DB.INTEGRATION.INT_FACT_USER_EVENT (
	EVENT_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	USER_SK NUMBER(38,0),
	CONTENT_SK NUMBER(38,0),
	DEVICEID VARCHAR(16777216),
	CONTENT_ID VARCHAR(16777216),
	EVENT_TS TIMESTAMP_NTZ(9) NOT NULL,
	EVENT_DATE DATE NOT NULL,
	EVENTNAME VARCHAR(16777216),
	TIMESPENT FLOAT,
	BATCH_ID NUMBER(38,0) NOT NULL,
	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL,
	primary key (EVENT_SK)
);
