create or replace TABLE INSHORTS_DB.INTEGRATION.INT_DIM_USER (
	USER_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	DEVICEID VARCHAR(16777216) NOT NULL,
	LANG VARCHAR(16777216),
	DISTRICT VARCHAR(16777216),
	PLATFORM VARCHAR(16777216),
	INSTALL_DT DATE,
	CAMPAIGN_ID VARCHAR(16777216),
	RECORD_HASH NUMBER(38,0),
	EFFECTIVE_START_DT DATE NOT NULL,
	EFFECTIVE_END_DT DATE NOT NULL,
	IS_CURRENT BOOLEAN NOT NULL,
	BATCH_ID NUMBER(38,0) NOT NULL,
	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL,
	UPDATED_TS TIMESTAMP_NTZ(9),
	primary key (USER_SK)
);
