create or replace TABLE INSHORTS_DB.INTEGRATION.INT_DIM_DATE (
	DATE_KEY DATE NOT NULL,
	YEAR NUMBER(38,0),
	MONTH NUMBER(38,0),
	WEEK NUMBER(38,0),
	DAY NUMBER(38,0),
	BATCH_ID NUMBER(38,0) NOT NULL,
	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL,
	primary key (DATE_KEY)
);
