create or replace TABLE INSHORTS_DB.REPORTING.DAILY_USER_REPORT (
	EVENT_DATE DATE,
	DAU NUMBER(38,0),
	AVG_TIME_SPENT NUMBER(38,0),
	AVG_ARTICLES_READ NUMBER(38,0),
	POWER_USERS NUMBER(38,0),
	ACTIVE_USERS NUMBER(38,0),
	CASUAL_USERS NUMBER(38,0),
	BATCH_ID VARCHAR(16777216) NOT NULL,
	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL
);
