create or replace TABLE INSHORTS_DB.REPORTING.EVENT_FUNNEL_SEGMENTED (
	EVENT_DATE DATE,
	USER_SEGMENT VARCHAR(16777216),
	SHOWN_USERS NUMBER(38,0),
	OPENED_USERS NUMBER(38,0),
	FRONT_READ_USERS NUMBER(38,0),
	BACK_READ_USERS NUMBER(38,0),
	SHARED_USERS NUMBER(38,0),
	SHOWN_TO_OPENED_CTR NUMBER(10,4),
	OPENED_TO_FRONT_RATE NUMBER(10,4),
	FRONT_TO_BACK_RATE NUMBER(10,4),
	DEEP_READ_RATE NUMBER(10,4),
	SHARE_RATE NUMBER(10,4),
	BATCH_ID VARCHAR(16777216) NOT NULL,
	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL
);
