create or replace TABLE INSHORTS_DB.REPORTING.ROLLING_ACTIVE_USERS (
	EVENT_DATE DATE,
	WAU NUMBER(38,0),
	MAU NUMBER(38,0),
	WAU_MAU_RATIO NUMBER(5,2),
	BATCH_ID VARCHAR(16777216) NOT NULL,
	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL
);
