create or replace TABLE INSHORTS_DB.REPORTING.SEGMENT_RETENTION_REPORT (
	INSTALL_DT DATE,
	USER_SEGMENT VARCHAR(16777216),
	COHORT_USERS NUMBER(38,0),
	D1_RETENTION_PCT NUMBER(5,2),
	W1_RETENTION_PCT NUMBER(5,2),
	M1_RETENTION_PCT NUMBER(5,2),
	BATCH_ID VARCHAR(16777216) NOT NULL,
	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL
);
