create or replace TABLE INSHORTS_DB.REPORTING.USER_RETENTION (
	INSTALL_DT DATE,
	DAY_NUMBER NUMBER(9,0),
	RETAINED_USERS NUMBER(18,0),
	BATCH_ID VARCHAR(16777216) NOT NULL,
	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL
);
