create or replace TABLE INSHORTS_DB.SYS_AUDIT.DQ_RULES (
	RULE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TARGET_TABLE VARCHAR(16777216) NOT NULL,
	TARGET_COLUMN VARCHAR(16777216),
	CHECK_TYPE VARCHAR(50) NOT NULL,
	RULE_EXPRESSION VARCHAR(16777216) NOT NULL,
	THRESHOLD FLOAT,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (RULE_ID)
);
