create or replace TABLE INSHORTS_DB.SYS_AUDIT.INGESTION_OBJECT_MAPPING (
	INGESTION_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	TARGET_TABLE_NAME VARCHAR(16777216) NOT NULL,
	SOURCE_STAGE VARCHAR(16777216) NOT NULL,
	FILE_PATTERN VARCHAR(16777216) NOT NULL,
	FILE_DELIMITER VARCHAR(16777216) NOT NULL,
	FILE_EXTENSION VARCHAR(16777216) NOT NULL,
	CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint UK_TARGET unique (TARGET_TABLE_NAME)
);
