create or replace TABLE INSHORTS_DB.SYS_AUDIT.PROCESS_MASTER (
	PROCESS_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	PROCESS_NAME VARCHAR(16777216),
	CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (PROCESS_NAME)
);
