USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION GCS_INT_NIS
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = GCS
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('gcs://nis_interview_task_de/');
